"""
Equivalence check for the nis_util.py refactor (TODO #5).

Compares, byte for byte, the .mac macro text generated by the OLD
nis_util (frozen snapshot next to this file: nis_util_old.py) and the
NEW one (nis_util.py at the repo root) for every wrapper, using
deterministic fake temp-file names and a no-op fake `subprocess.call`.
Run it any time nis_util.py changes: a macro body may only differ from
the snapshot if the change is deliberate (in that case update the
snapshot with the new body).

Also:
  - round-trip tests of the new code with a fake nis_ar that fills the
    .ini result file (verifies placeholder substitution + parsing),
  - the two intentional behaviour fixes (get_position without a piezo,
    set_position pos_piezo),
  - PermissionError tolerance when cleaning up locked .mac files.
"""
import importlib.util
import os
import re
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
# this file lives in <root>/autofrap/autofrap_bitsnpieces/
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, ROOT)

NIS = r'C:\fake\nis_ar.exe'
TMPDIR = tempfile.gettempdir()


def load_module(path, name):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


old = load_module(os.path.join(HERE, 'nis_util_old.py'), 'nis_util_old')
new = load_module(os.path.join(ROOT, 'nis_util.py'), 'nis_util_new')

# ------------------------------------------------------------------
# fakes

CALLS = []
MAC_BODIES = []


class FakeNTF:
    """deterministic NamedTemporaryFile stand-in (same names every run)"""
    counter = 0

    def __init__(self, suffix='.mac', delete=False):
        FakeNTF.counter += 1
        self.name = os.path.join(TMPDIR, 'nistest_%d%s' % (FakeNTF.counter, suffix))
        self._f = open(self.name, 'wb')

    def writelines(self, lines):
        self._f.writelines(lines)

    def close(self):
        if not self._f.closed:
            self._f.close()


def _clean_fakes():
    global FAKE_INI
    FAKE_INI = None
    FakeNTF.counter = 0
    CALLS.clear()
    MAC_BODIES.clear()
    for f in os.listdir(TMPDIR):
        if f.startswith('nistest_'):
            os.remove(os.path.join(TMPDIR, f))


FAKE_INI = None  # if set, the fake nis_ar writes this into the .ini


def fake_call(cmdline):
    CALLS.append(cmdline)
    mac = cmdline.split()[-1].strip('"')
    MAC_BODIES.append(open(mac, 'rb').read())  # snapshot: nis_ar owns the file now
    if FAKE_INI is not None:
        body = MAC_BODIES[-1].decode('utf-8')
        m = re.search(r'Int_SetKey(?:String|Value)\("([^"]+)"', body)
        assert m, 'no ini reference found in macro: %s' % body
        with open(m.group(1), 'w', encoding='utf-8') as fh:
            fh.write(FAKE_INI)
    return 0


def run_capture(mod, fn, clean=True):
    """run fn (from module mod) with fakes; return (mac_body_bytes, result_or_exc)"""
    if clean:
        _clean_fakes()
    mod.NamedTemporaryFile = FakeNTF
    real_call = subprocess.call
    subprocess.call = fake_call
    try:
        try:
            result = fn(mod)
        except Exception as e:  # expected for ini fns with an empty ini
            result = e
    finally:
        subprocess.call = real_call
    assert len(CALLS) == 1, 'expected exactly one nis_ar call, got %r' % CALLS
    body = MAC_BODIES[-1]
    mac = CALLS[0].split()[-1].strip('"')
    # cleanup happened inside the wrapper
    assert not os.path.exists(mac), 'temp .mac not cleaned up: %s' % mac
    return body, result


def run_roundtrip(mod, fn, ini_content):
    """run fn with the fake nis_ar writing `ini_content` into the .ini"""
    global FAKE_INI
    _clean_fakes()          # resets FAKE_INI first
    FAKE_INI = ini_content
    body, result = run_capture(mod, fn, clean=False)
    assert not isinstance(result, Exception), 'unexpected exception: %r' % result
    return body, result


# ------------------------------------------------------------------
# 1. byte-for-byte macro body equivalence (old vs new)

CASES = [
    ('export_nd2_to_tiff', lambda m: m.export_nd2_to_tiff(NIS, '/data/img.nd2', out_dir='/tmp', combine_c=False)),
    ('export_nd2_to_tiff_c', lambda m: m.export_nd2_to_tiff(NIS, '/data/img.nd2', out_dir='/tmp', combine_c=True, combine_t=True, combine_yx=True)),
    ('backup_optical_configurations', lambda m: m.backup_optical_configurations(NIS, '/tmp/bk.xml')),
    ('do_autofocus_defaults', lambda m: m.do_autofocus(NIS)),
    ('do_autofocus_custom', lambda m: m.do_autofocus(NIS, step_coarse=5.0, step_fine=0.5, focus_criterion=3, focus_with_piezo=True)),
    ('set_optical_configuration', lambda m: m.set_optical_configuration(NIS, 'FRAPPA')),
    ('do_large_image_scan_close', lambda m: m.do_large_image_scan(NIS, '/tmp/out.nd2', 1, 2, 3, 4, overlap=0.2, registration=True, z_count=3, z_step=0.7, close=True)),
    ('do_large_image_scan_noclose', lambda m: m.do_large_image_scan(NIS, '/tmp/out.nd2', 1, 2, 3, 4, z_count=1, close=False)),
    ('get_camera_format', lambda m: m.get_camera_format(NIS)),
    ('get_resolution', lambda m: m.get_resolution(NIS)),
    ('get_rotation_matrix', lambda m: m.get_rotation_matrix(NIS)),
    ('get_cam_rotation', lambda m: m.get_cam_rotation(NIS)),
    ('get_optical_confs', lambda m: m.get_optical_confs(NIS)),
    ('set_position_xy', lambda m: m.set_position(NIS, pos_xy=(1.5, -2.25))),
    ('set_position_z_rel', lambda m: m.set_position(NIS, pos_z=3.0, relative_z=True)),
    ('get_position', lambda m: m.get_position(NIS)),
    ('run_current_nd_experiment_plain', lambda m: m.run_current_nd_experiment(NIS)),
    ('run_current_nd_experiment_save', lambda m: m.run_current_nd_experiment(NIS, outfile='/tmp/a/b.nd2', open_after=False, progress_bar=False)),
    ('run_stimulation_experiment', lambda m: m.run_stimulation_experiment(NIS)),
    ('open_image', lambda m: m.open_image(NIS, '/tmp/img.nd2')),
    ('get_current_document', lambda m: m.get_current_document(NIS)),
    ('save_current_document', lambda m: m.save_current_document(NIS, '/tmp/out.nd2')),
    ('close_current_document_discard', lambda m: m.close_current_document(NIS)),
    ('close_current_document_yes', lambda m: m.close_current_document(NIS, save='yes')),
    ('close_current_document_ask', lambda m: m.close_current_document(NIS, save='ask')),
    ('add_polygon_roi_green', lambda m: m.add_polygon_roi(NIS, [(0, 0), (10, 0), (10, 5), (0, 5)], color='green')),
    ('add_polygon_roi_intcolor', lambda m: m.add_polygon_roi(NIS, [(1.5, 2.25), (3.75, 4.0), (5.0, 0.125)], color=255)),
    ('set_roi_type', lambda m: m.set_roi_type(NIS, 7, 3)),
    ('delete_roi', lambda m: m.delete_roi(NIS, 7)),
    ('get_roi_count', lambda m: m.get_roi_count(NIS)),
    ('get_roi_info', lambda m: m.get_roi_info(NIS, 7)),
    ('NDAcquisition_run', lambda m: m.NDAcquisition('/tmp/out.nd2').run(NIS)),
]


def ndacq_full(mod):
    a = mod.NDAcquisition('/tmp/out.nd2')
    a.t = '1'
    a.add_points([(1.0, 2.0, 0.0), (3.0, 4.0, 0.5)])
    a.set_z(0.0, 10.0, 2.0, device_name='Piezo')
    a.add_c('FRAPPA')
    a.add_c('Brightfield')
    a.prepare(NIS)


CASES.append(('NDAcquisition_prepare_full', ndacq_full))

print('=== macro body equivalence (old vs new) ===')
n_ok, n_fail = 0, 0
for name, fn in CASES:
    body_old, _ = run_capture(old, fn)
    body_new, _ = run_capture(new, fn)
    if body_old == body_new:
        n_ok += 1
        print('  OK   %s (%d bytes)' % (name, len(body_new)))
    else:
        n_fail += 1
        print('  DIFF %s' % name)
        import difflib
        d = difflib.unified_diff(
            body_old.decode('utf-8').splitlines(),
            body_new.decode('utf-8').splitlines(),
            'old', 'new', lineterm='')
        for line in d:
            print('    | ' + line)

# set_position with all-None args: no macro at all
real_call = subprocess.call
for mod, label in ((old, 'old'), (new, 'new')):
    _clean_fakes()
    mod.NamedTemporaryFile = FakeNTF
    subprocess.call = fake_call
    try:
        mod.set_position(NIS)
        assert len(CALLS) == 0, '%s: set_position(None,None,None) should not run a macro' % label
    finally:
        subprocess.call = real_call
print('  OK   set_position no-op (no macro) both old and new')

print('\nequivalence: %d OK, %d DIFF' % (n_ok, n_fail))
assert n_fail == 0


# ------------------------------------------------------------------
# 2. round-trip: placeholder substitution + ini parsing (new code)

print('\n=== round-trip (fake nis_ar fills the .ini) ===')
RT = [
    ('get_camera_format', '[res]\nfmt_live = LiveFormat\nfmt_capture = 3x8_Kaiser_Full_Area_2.5x\n',
     lambda m: m.get_camera_format(NIS), ('LiveFormat', '3x8_Kaiser_Full_Area_2.5x')),
    ('get_resolution', '[res]\nxres = 1024\nyres = 1024\nsiz = 13.0\nmag = 20.0\n',
     lambda m: m.get_resolution(NIS), (1024.0, 1024.0, 13.0, 20.0)),
    ('get_rotation_matrix', '[res]\na11 = 0.999\na12 = -0.01\na21 = 0.01\na22 = 0.999\n',
     lambda m: m.get_rotation_matrix(NIS), (0.999, -0.01, 0.01, 0.999)),
    ('get_cam_rotation', '[res]\nrotation = 0.0\nrotation2 = 90.0\n',
     lambda m: m.get_cam_rotation(NIS), (0.0, 90.0)),
    ('get_position_z1', '[pos]\nz1 = 4.0\nx = 1.5\ny = -2.5\nz0 = 3.0\n',
     lambda m: m.get_position(NIS), (1.5, -2.5, 3.0, 4.0)),
    ('get_position_no_z1', '[pos]\nx = 1.5\ny = -2.5\nz0 = 3.0\n',
     lambda m: m.get_position(NIS), (1.5, -2.5, 3.0, None)),
    ('get_optical_confs', '[oc]\ncount = 2\nconf0 = FRAPPA\nconf1 = Brightfield\n',
     lambda m: m.get_optical_confs(NIS), ['FRAPPA', 'Brightfield']),
    ('get_current_document', '[doc]\npath = ND Acquisition\n',
     lambda m: m.get_current_document(NIS), 'ND Acquisition'),
    ('add_polygon_roi', '[roi]\nid = 7\n',
     lambda m: m.add_polygon_roi(NIS, [(0, 0), (10, 0), (10, 5)], color='green'), 7),
    ('get_roi_count', '[roi]\ncount = 3\n',
     lambda m: m.get_roi_count(NIS), 3),
    ('get_roi_info', '[roi]\nl = 1\nt = 2\nr = 3\nb = 4\ncx = 5\ncy = 6\nminf = 7\nmaxf = 8\nrot = 0.25\ncol = 65280\n',
     lambda m: m.get_roi_info(NIS, 7),
     {'bbox_l': 1, 'bbox_t': 2, 'bbox_r': 3, 'bbox_b': 4, 'center_x': 5, 'center_y': 6,
      'min_feret': 7, 'max_feret': 8, 'rotation': 0.25, 'color': 65280}),
]
for name, ini, fn, expected in RT:
    _, result = run_roundtrip(new, fn, ini)
    status = 'OK  ' if result == expected else 'FAIL'
    print('  %s %s -> %r' % (status, name, result))
    assert result == expected, '%s: expected %r' % (name, expected)

# ------------------------------------------------------------------
# 3. intentional behaviour fixes

print('\n=== behaviour fixes ===')

# 3a. old get_position crashes (TypeError: float(None)) when no piezo key
body, res = run_capture(old, lambda m: m.get_position(NIS))
assert isinstance(res, Exception), 'old get_position unexpectedly succeeded'
print('  OK   old get_position without piezo raises: %r (fixed in new: returns z1=None)' % res)

# 3b. old set_position(pos_piezo=...) formatted pos_z instead of pos_piezo
body_old, _ = run_capture(old, lambda m: m.set_position(NIS, pos_piezo=1.0))
body_new, _ = run_capture(new, lambda m: m.set_position(NIS, pos_piezo=1.0))
assert body_old.decode() == 'StgMovePiezoZ(None,0);', body_old
assert body_new.decode() == 'StgMovePiezoZ(1.0,0);', body_new
print('  OK   set_position pos_piezo: old=%r new=%r (fixed)'
      % (body_old.decode(), body_new.decode()))

# 3c. new set_position branches produce the expected bodies
for args, expected in [
    (dict(pos_xy=(1.5, -2.25)), 'StgMoveXY(1.5,-2.25,0);'),
    (dict(pos_z=3.0, relative_z=True), 'StgMoveMainZ(3.0,1);'),
    (dict(pos_piezo=1.0, relative_piezo=True), 'StgMovePiezoZ(1.0,1);'),
    (dict(pos_xy=(0, 0), pos_z=2.0, pos_piezo=1.0),
     'StgMoveXY(0,0,0);\nStgMoveMainZ(2.0,0);\nStgMovePiezoZ(1.0,0);'),
]:
    body, _ = run_capture(new, lambda m, a=args: m.set_position(NIS, **a))
    assert body.decode() == expected, (body.decode(), expected)
    print('  OK   set_position %s -> %r' % (args, body.decode()))

# ------------------------------------------------------------------
# 4. cleanup tolerates a locked .mac (NIS keeps failed macros locked)

print('\n=== cleanup tolerance ===')
real_remove = os.remove
real_call = subprocess.call


def flaky_remove(p):
    if str(p).endswith('.mac'):
        raise PermissionError(32, 'simulated NIS lock')
    real_remove(p)


_clean_fakes()
new.NamedTemporaryFile = FakeNTF
os.remove = flaky_remove
subprocess.call = fake_call
try:
    new.set_position(NIS, pos_xy=(1, 2))   # must not raise
finally:
    os.remove = real_remove
    subprocess.call = real_call
print('  OK   _cleanup swallowed PermissionError on .mac removal')

# and normal runs still remove both temp files
body, _ = run_capture(new, lambda m: m.get_roi_count(NIS))
leftovers = [f for f in os.listdir(TMPDIR) if f.startswith('nistest_')]
assert not leftovers, 'leftover temp files: %r' % leftovers
print('  OK   both temp files removed in the normal case')

print('\nALL CHECKS PASSED')
